### ISSUE TITLE
please make readme

### ISSUE THREAD

**Issue by koek67** [illegalprime/kthulu#1]
the only language i know is 3ngL15h

**Comment by illegalprime** [comment]
@koek67 do you want to contribute?

**Comment by koek67** [comment]
Yes

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=5.0.2&source=email_footer_2] On Tue, Mar 01, 2016 at 1:59 PM, Michael Eden < notifications@github.com [notifications@github.com] > wrote:
@koek67 [https://github.com/koek67] do you want to contribute?

—
Reply to this email directly or view it on GitHub
[https://github.com/illegalprime/kthulu/issues/1#issuecomment-190852491] .[https://github.com/notifications/beacon/ABdNrWEwJA19DGcWfEDZohy5Sufx-Lupks5ppIyjgaJpZM4HhKjs.gif]
